# Remove this when it should be deployed
# spring.cloud.gcp.datastore.host=localhost:8081
# export DATASTORE_USE_PROJECT_ID_AS_APP_ID=true use this variable to

spring.cloud.gcp.datastore.project-id=primeiroprojeto-489312
spring.cloud.gcp.datastore.database-id=projetoindividual